name: Tests and Code coverage

on:
  pull_request:
  push:
    branches:
      - development
      - master

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17
      - name: Run tests with coverage
        run: make test-coverage
      - name: Exclude files from coverage report
        run: |
          filepaths+=" $(find ./ -type f -name '*.go' -exec grep -l 'DONOTCOVER' {} \;)"
          filepaths+=" $(find ./ -type f -name '*.pb.go')"
          filepaths+=" $(find ./ -type f -name '*.pb.gw.go')"
          for filepath in ${filepaths}; do
            filepath=$(echo ${filepath} | sed 's/^./github.com\/sentinel-official\/hub/g')
            echo "Excluding file ${filepath} from coverage report..."
            sed -i "/$(echo ${filepath} | sed 's/\//\\\//g')/d" ./coverage.txt
          done
      - uses: codecov/codecov-action@v1.5.2
        with:
          file: ./coverage.txt
